# Generated by Django 5.1.7 on 2025-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drr', '0003_blogpostcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategory',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
