# Generated by Django 5.1.7 on 2025-03-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drr', '0005_remove_blogpostcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategory',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
