# Generated by Django 5.1.7 on 2025-03-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drr', '0006_blogpostcategory_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcategory',
            name='icon',
        ),
    ]
