# Generated by Django 5.1.7 on 2025-03-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drr', '0007_remove_blogpostcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategory',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
