# Generated by Django 5.1.7 on 2025-03-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drr', '0008_blogpostcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
