# Generated by Django 5.1.7 on 2025-04-17 20:37

import myproject.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drr', '0010_blogpost_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Cover image stored in DigitalOcean Spaces', null=True, storage=myproject.storages.SpacesMediaStorage(), upload_to='cover_photos/%Y/%m/%d/'),
        ),
    ]
