# Generated by Django 5.1.7 on 2025-04-17 21:02

import myproject.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drr', '0011_alter_blogpost_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Category image stored in DigitalOcean Spaces', null=True, storage=myproject.storages.SpacesMediaStorage(), upload_to='category_images/%Y/%m/%d/'),
        ),
    ]
