# Generated by Django 5.1.7 on 2025-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='cover_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
