# Generated by Django 5.1.7 on 2025-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdetails_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
