# Generated by Django 5.1.7 on 2025-04-18 07:46

import drr.models
import myproject.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userdetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image stored in DigitalOcean Spaces', null=True, storage=myproject.storages.SpacesMediaStorage(), upload_to=drr.models.UploadToPath('user_cover_images')),
        ),
    ]
